function y = toggle_switch_self_edges(x, gamma, L, delta, theta, n1, n2)

y = [-gamma(1) * x(1) + H_minus(x(2), L(2,1), delta(2,1), theta(2,1), n1) .* ...
                        H_plus(x(1), L(1,1), delta(1,1), theta(1,1), n1); ...
     -gamma(2) * x(2) + H_minus(x(1), L(1,2), delta(1,2), theta(1,2), n2) .* ...
                        H_plus(x(2), L(2,2), delta(2,2), theta(2,2), n2)];
end
